"""create initial community schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-23 07:21:54.666989
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

REGIONS = (
    ("seoul", True),
    ("busan", True),
    ("gyeonggi", False),
    ("incheon", False),
    ("daejeon", False),
    ("daegu", False),
    ("gwangju", False),
    ("ulsan", False),
    ("gangwon", False),
    ("jeju", False),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    regions = op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('name', name=op.f('uq_regions_name'))
    )
    op.bulk_insert(
        regions,
        [{"name": name, "is_enabled": is_enabled} for name, is_enabled in REGIONS],
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_users_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('nickname', name=op.f('uq_users_nickname')),
    sa.UniqueConstraint('uuid', name=op.f('uq_users_uuid'))
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.Enum('COMMUNITY_POST', 'MOGACKO', 'EVENT', name='commenttargettype', native_enum=False, length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("target_type IN ('COMMUNITY_POST', 'MOGACKO', 'EVENT')", name='ck_comments_target_type'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], name=op.f('fk_comments_parent_comment_id_comments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments')),
    sa.UniqueConstraint('uuid', name='uq_comments_uuid')
    )
    op.create_index('ix_comments_parent_comment_id', 'comments', ['parent_comment_id'], unique=False)
    op.create_index('ix_comments_target_created', 'comments', ['target_type', 'target_id', 'created_at'], unique=False)
    op.create_index('ix_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('board', sa.Enum('notice', 'question', 'talk', name='communitypostboard', native_enum=False, length=20), nullable=False),
    sa.Column('category', sa.Enum('free', 'retrospective', 'recruit', name='communitypostcategory', native_enum=False, length=30), nullable=True),
    sa.Column('title', sa.String(length=25), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('char_length(body) <= 3000', name='ck_community_posts_body_length'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_community_posts_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_community_posts_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_posts')),
    sa.UniqueConstraint('uuid', name=op.f('uq_community_posts_uuid'))
    )
    op.create_index('ix_community_posts_author_id', 'community_posts', ['author_id'], unique=False)
    op.create_index('ix_community_posts_region_board_category_created', 'community_posts', ['region_id', 'board', 'category', 'created_at'], unique=False)
    op.create_index('ix_community_posts_region_board_created', 'community_posts', ['region_id', 'board', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_community_posts_region_board_created', table_name='community_posts')
    op.drop_index('ix_community_posts_region_board_category_created', table_name='community_posts')
    op.drop_index('ix_community_posts_author_id', table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index('ix_comments_user_id', table_name='comments')
    op.drop_index('ix_comments_target_created', table_name='comments')
    op.drop_index('ix_comments_parent_comment_id', table_name='comments')
    op.drop_table('comments')
    op.drop_table('users')
    op.drop_table('regions')
    # ### end Alembic commands ###
